Used `with` construct properly in both `Reader` and `Writer` class.
openebs/easy-jupyter pull request #7
Opened 2018-05-24 19:54 UTC by shubhambhattar

- `file.close()` was used in `Reader` class which was redundant.
- `with` keyword was added in `Writer` class.

2018-05-25 04:57 UTC, utkarshmani1997 approved these changes
LGTM

2018-05-25 05:25 UTC, satyamz requested changes

2018-05-25 05:25 UTC, satyamz commented on openebs_utils.py
> +                # time.sleep(1)
Can you remove this comment? We don't need it.

2018-05-25 07:18 UTC, shubhambhattar commented
Yes. I'll remove the following line tonight:

`# time.sleep(1)`



On Fri, May 25, 2018, 10:55 Satyam Zode <notifications@github.com> wrote:

> *@satyamz* requested changes on this pull request.
> ------------------------------
>
> In openebs_utils.py
> <https://github.com/openebs/easy-jupyter/pull/7#discussion_r190793839>:
>
> > @@ -35,12 +34,11 @@ def __init__(self, file_name):
>
>      def run(self):
>          # print(self.file_name)
> -        file = open(self.file_name, 'w')
> -        for i in range(1, 2000000):
> -            print("Writing ", i)
> -            file.write(str(i))
> -            # time.sleep(1)
> -        file.close()
> +        with open(self.file_name, 'w') as file:
> +            for i in range(1, 2000000):
> +                print("Writing ", i)
> +                file.write(str(i))
> +                # time.sleep(1)
>
> Can you remove this comment? We don't need it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openebs/easy-jupyter/pull/7#pullrequestreview-123247526>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKlSahd4vkycy8wWbtSWNLgWVGai4jt5ks5t15XPgaJpZM4UM4jA>
> .
>

2018-05-25 13:41 UTC, vharsh approved these changes

2018-05-25 14:07 UTC, shubhambhattar reviewed
Removed the comment.

2018-05-28 13:49 UTC, satyamz approved these changes

2018-05-28 13:49 UTC, merged